# Generated by Django 5.1.1 on 2024-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claSS', models.CharField(choices=[('FIVE', 'FIVE'), ('SIX', 'SIX'), ('SEVEN', 'SEVEN'), ('EIGHT', 'EIGHT')], max_length=12)),
                ('claSS_slug', models.SlugField(max_length=12)),
                ('salary', models.IntegerField()),
                ('day_perweek', models.CharField(choices=[('2 days', 2), ('5 days', 5), ('6 days', 6)], max_length=13)),
                ('avilable', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('tution_duration', models.CharField(max_length=40, null=True)),
                ('no_of_student', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
