# Generated by Django 5.1.1 on 2024-09-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tution', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
                ('tutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tution.tution')),
            ],
            options={
                'unique_together': {('teachers', 'tutions')},
            },
        ),
    ]
